---
# Ansible playbook
#

- name: Common settings
  hosts: all
  roles:
    - role: bootstrap
      tags:
        - bootstrap

    - role: mycooltools
      tags:
        - mycooltools

    - role: webserver
      tags:
        - webserver

    - role: helloworldpage
      tags:
        - helloworldpage

  tags:
    - common

...
